CREATE TABLE palavras (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    significado VARCHAR2(500)
);

-- Insere alguns registros
INSERT INTO palavras (nome, significado) VALUES ('Escarlate', 'Vermelho intenso');
INSERT INTO palavras (nome, significado) VALUES ('Aurora', 'Luz do amanhecer');

-- Confirma no Oracle
COMMIT;