CREATE TABLE frase (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(255) NOT NULL,
    palavra_id NUMBER NOT NULL,
    CONSTRAINT fk_frase_palavra
        FOREIGN KEY (palavra_id)
        REFERENCES palavra(id)
);